Algoritmo "Abdominais na Lagoa"

var
   abdominal, volta : inteiro

inicio

   para volta de 1 ate 5 faca
      escreval ("")
      escreval ("VOLTA Nº.", volta,":")
      para abdominal de 1 ate 10 faca
         se abdominal < 10 entao
            escreva (abdominal, "ª abdominal, ")
         senao
            escreva (abdominal, "ª abdominal.")
         fimse
      fimpara
      escreval ("")
   fimpara

Fimalgoritmo