Algoritmo "Lista de Exercícios (41)"
// Disciplina  :  [Algoritmos e Lógica de Programação] 
//  
// Descrição   : Operações com estruturas de repetição
// Autor(a)    : Plinio Petrika Paini
// Data atual  : 06/02/2018

Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Série de Bergamaschi:")
escreval ("Não sei o que é nem como faz...")
escreval ("FODA-SE")

Fimalgoritmo