Algoritmo "Sucessor e antecessor"

//(d) Criar um algoritmo e fluxograma que leia 2 números inteiros
//    e imprimir seu sucessor e antecessor.

var
   n1, n2 : inteiro

inicio

   escreval ("Digite um número inteiro:")
   leia (n1)
   escreval ("Digite outro número inteiro:")
   leia (n2)
   escreval ("O sucessor do número", n1, " é", n1+1, " e seu antecessor é", n1-1)
   escreval ("e o sucessor do número", n2, " é", n2+1, " e seu antecessor é", n2-1)

Fimalgoritmo